spring:
  application:
    name: online-reserve
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  jackson:
#    time-zone: Asia/Tashkent

#telegram:
#  bots:
#    booking:
#      username: ${BOOKING_BOT_USERNAME:dinetime_monitoring_bot}
#      token: ${BOOKING_BOT_TOKEN:6897439094:AAFVfOkYBAiNg-nPN6EPd3Q77VSMq8bbBzs}

springdoc:
  api-docs:
    path: /api-docs